fail_fast: false
default_install_hook_types: [pre-commit, pre-push, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
        exclude: "CHANGELOG.md|LICENSE"

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        name: lint commit message for Conventional Commits compliance
        additional_dependencies:
          - '@commitlint/config-conventional'
        stages: [commit-msg]
        args:
          - "--extends=@commitlint/config-conventional"

  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest before push
        entry: pytest
        language: system
        stages: [pre-push]
        pass_filenames: false
        always_run: true
