[command]
name = "test-prompt"
description = "Test prompt for writer tests"
enabled = true
tags = [
    "testing",
]

[command.arguments.required]

[command.arguments.optional]

[command.body]
text = "# Test Prompt\n\nThis is a test prompt."

[command.meta]
agent = "gemini-cli"
agent_display_name = "Gemini CLI"
command_dir = ".gemini/commands"
command_format = "toml"
command_file_extension = ".toml"
source_prompt = "test-prompt"
source_path = "/tmp/pytest-of-damien/pytest-18/test_writer_generates_commands0/prompts/test-prompt.md"
