#!/usr/bin/env python3
"""
Low-effort font embedding script for playbook-site.

Downloads DM Sans fonts from Google Fonts and embeds them locally,
replacing Google Fonts CDN links with local @font-face declarations.
"""

import os
import re
import json
import urllib.request
import urllib.parse
from pathlib import Path

# Configuration
FONT_FAMILY = "DM Sans"
FONT_DIR = Path(__file__).parent / "assets" / "fonts"
HTML_DIR = Path(__file__).parent
CSS_FILE = HTML_DIR / "assets" / "css" / "styles.css"

# Google Fonts API endpoint
GF_API_BASE = "https://fonts.googleapis.com/css2"


def download_font_file(url: str, output_path: Path) -> None:
    """Download a font file from URL."""
    print(f"  Downloading {output_path.name}...")
    # Add User-Agent header for font downloads
    req = urllib.request.Request(url, headers={
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    })
    with urllib.request.urlopen(req) as response:
        with open(output_path, 'wb') as f:
            f.write(response.read())


def get_font_css_from_google() -> str:
    """Fetch the CSS from Google Fonts API."""
    # Manually construct URL to preserve @ symbol in variable font syntax
    # urlencode would encode @ as %40 which breaks the format
    font_spec = "DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000"
    url = f"{GF_API_BASE}?family={font_spec}&display=swap"

    print(f"Fetching font CSS from Google Fonts...")
    # Google Fonts requires a User-Agent header
    req = urllib.request.Request(url, headers={
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    })
    with urllib.request.urlopen(req) as response:
        return response.read().decode('utf-8')


def parse_google_fonts_css(css: str) -> list:
    """Parse Google Fonts CSS to extract font file URLs and metadata."""
    fonts = []

    # Match @font-face blocks
    font_face_pattern = r'@font-face\s*\{([^}]+)\}'

    for match in re.finditer(font_face_pattern, css, re.DOTALL):
        block = match.group(1)

        # Extract font-family
        family_match = re.search(r"font-family:\s*['\"]([^'\"]+)['\"]", block)
        if not family_match:
            continue

        # Extract font-weight
        weight_match = re.search(r"font-weight:\s*(\d+)", block)
        weight = weight_match.group(1) if weight_match else "400"

        # Extract font-style
        style_match = re.search(r"font-style:\s*(\w+)", block)
        style = style_match.group(1) if style_match else "normal"

        # Extract font file URLs (prefer woff2, then woff, then ttf)
        url_match = re.search(r"url\(([^)]+)\)\s+format\(['\"]woff2['\"]\)", block)
        if not url_match:
            url_match = re.search(r"url\(([^)]+)\)\s+format\(['\"]woff['\"]\)", block)
        if not url_match:
            url_match = re.search(r"url\(([^)]+)\)\s+format\(['\"]truetype['\"]\)", block)

        if url_match:
            font_url = url_match.group(1).strip("'\"")
            fonts.append({
                "url": font_url,
                "weight": weight,
                "style": style,
                "family": family_match.group(1)
            })

    return fonts


def generate_font_face_css(fonts: list, base_path: str = "assets/fonts") -> str:
    """Generate @font-face CSS declarations for local fonts."""
    css_lines = ["/* Embedded DM Sans fonts - generated by embed-fonts.py */"]

    for font in fonts:
        # Generate filename from weight and style
        style_suffix = "italic" if font["style"] == "italic" else "regular"
        # Determine file extension from URL
        font_url = font["url"]
        if font_url.endswith('.woff2'):
            ext = 'woff2'
            format_type = 'woff2'
        elif font_url.endswith('.woff'):
            ext = 'woff'
            format_type = 'woff'
        else:
            ext = 'ttf'
            format_type = 'truetype'

        filename = f"dm-sans-{font['weight']}-{style_suffix}.{ext}"

        css_lines.append(f"""
@font-face {{
    font-family: '{font['family']}';
    src: url('{base_path}/{filename}') format('{format_type}');
    font-weight: {font['weight']};
    font-style: {font['style']};
    font-display: swap;
}}""")

    return "\n".join(css_lines)


def update_html_files(font_css: str) -> None:
    """Replace Google Fonts links in HTML files with embedded font CSS."""
    html_files = list(HTML_DIR.glob("*.html"))

    # Pattern to match Google Fonts link tags
    pattern = re.compile(
        r'<link[^>]*href=["\']https://fonts\.googleapis\.com/css2[^"\']*["\'][^>]*>',
        re.IGNORECASE
    )

    # Also match preconnect tags
    preconnect_pattern = re.compile(
        r'<link[^>]*rel=["\']preconnect["\'][^>]*fonts\.(googleapis|gstatic)\.com[^>]*>',
        re.IGNORECASE
    )

    for html_file in html_files:
        print(f"Updating {html_file.name}...")
        with open(html_file, 'r', encoding='utf-8') as f:
            content = f.read()

        original_content = content

        # Remove preconnect tags
        content = preconnect_pattern.sub('', content)

        # Check if embedded font style tag already exists
        existing_font_style = re.search(
            r'<style>\s*/\* Embedded DM Sans fonts.*?</style>',
            content, re.DOTALL
        )

        if existing_font_style:
            # Replace existing embedded font style
            content = content[:existing_font_style.start()] + \
                     f'<style>\n{font_css}\n    </style>' + \
                     content[existing_font_style.end():]
        elif pattern.search(content):
            # Remove Google Fonts link and insert embedded CSS
            content = pattern.sub('', content)

            # Insert font CSS in <head> before </head>
            head_close = content.find('</head>')
            if head_close != -1:
                # Find the last <link> or <style> tag in head to insert after
                head_section = content[:head_close]
                last_link = head_section.rfind('<link')
                last_style = head_section.rfind('<style')
                insert_pos = max(last_link, last_style)

                if insert_pos != -1:
                    # Find the end of that tag
                    tag_end = content.find('>', insert_pos) + 1
                    content = (content[:tag_end] + '\n    <style>\n' +
                              font_css + '\n    </style>' + content[tag_end:])
                else:
                    # Insert right before </head>
                    content = (content[:head_close] +
                              '\n    <style>\n' + font_css + '\n    </style>\n' +
                              content[head_close:])

        if content != original_content:
            with open(html_file, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  ✓ Updated {html_file.name}")


def main():
    """Main execution."""
    print("🚀 Embedding fonts for playbook-site...\n")

    # Create fonts directory
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Created fonts directory: {FONT_DIR}\n")

    # Fetch CSS from Google Fonts
    google_css = get_font_css_from_google()

    # Parse font URLs
    fonts = parse_google_fonts_css(google_css)
    print(f"\nFound {len(fonts)} font variants\n")

    # Deduplicate fonts by weight/style (keep first occurrence)
    # Google Fonts may return multiple files for same weight/style (different optical sizes)
    seen = {}
    unique_fonts = []
    for font in fonts:
        key = (font['weight'], font['style'])
        if key not in seen:
            seen[key] = True
            unique_fonts.append(font)

    print(f"Deduplicated to {len(unique_fonts)} unique weight/style combinations\n")
    fonts = unique_fonts

    # Download font files
    print("Downloading font files...")
    for font in fonts:
        style_suffix = "italic" if font["style"] == "italic" else "regular"
        # Determine file extension from URL
        font_url = font["url"]
        if font_url.endswith('.woff2'):
            ext = 'woff2'
        elif font_url.endswith('.woff'):
            ext = 'woff'
        else:
            ext = 'ttf'

        filename = f"dm-sans-{font['weight']}-{style_suffix}.{ext}"
        font_path = FONT_DIR / filename

        if not font_path.exists():
            download_font_file(font["url"], font_path)
        else:
            print(f"  Skipping {filename} (already exists)")

    # Generate @font-face CSS
    print("\nGenerating @font-face CSS...")
    font_css = generate_font_face_css(fonts)
    print(f"Generated {len(font_css)} characters of CSS with {font_css.count('@font-face')} @font-face declarations")

    # Update HTML files
    print("\nUpdating HTML files...")
    update_html_files(font_css)

    print("\n✅ Font embedding complete!")
    print(f"\nFont files saved to: {FONT_DIR}")
    print("HTML files updated to use embedded fonts.")


if __name__ == "__main__":
    main()
